services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./.mvn:/app/.mvn
    env_file:
      - .env
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
