services:
  - type: web
    name: upark-api
    env: docker                 # ← Change ici (au lieu de java)
    dockerfilePath: ./Dockerfile # ← ton Dockerfile reste utilisé
    plan: free
    region: frankfurt
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx512m

databases:
  - name: upark-db
    databaseName: upark_db
    user: upark_user
    region: frankfurt
    plan: free