services:
  - type: web
    name: upark-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx512m
      - key: DATABASE_URL
        fromDatabase:
          name: upark-db
          property: connectionString

databases:
  - name: upark-db
    databaseName: upark_db
    user: upark_db_user
    region: frankfurt
    plan: free