spring.application.name=upark
server.port=${PORT:8080}

# Spring Boot lit automatiquement SPRING_DATASOURCE_URL + USERNAME + PASSWORD
# → Plus besoin de rien toucher
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Logging utile
logging.level.org.hibernate.SQL=debug
logging.level.com.zaxxer.hikari=debug