spring.application.name=upark
server.port=${PORT:8080}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# HikariCP - ultra léger pour Supabase gratuit
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=20000

# SSL obligatoire sur Supabase
spring.datasource.hikari.data-source-properties=sslmode=require

# Évite la requête lourde au démarrage
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Logs utiles
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.com.zaxxer.hikari=DEBUG